function [fitresult, gof] = Fit_Energia_Rigidez_Colmenares(E, Ks1)
%CREATEFIT(E,KS1)
%  Create a fit.
%
%  Data for 'Fit EnergíaDisipada_Rigidez_Col' fit:
%      X Input : E
%      Y Output: Ks1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Dec-2022 00:18:43


%% Fit: 'Fit EnergíaDisipada_Rigidez_Col'.
[xData, yData] = prepareCurveData( E, Ks1 );

% Set up fittype and options.
ft = fittype( 'power2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
% opts.Algorithm = 'Levenberg-Marquardt';
opts.Display = 'Off';
opts.StartPoint = [0.965701050754521 -0.0315935851371883 -1.19206498984664e-05];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'Fit EnergíaDisipada_Rigidez_Col' );
% h = plot( fitresult, xData, yData, 'predobs', 0.9 );
% legend( h, 'Ks1 vs. E', 'Fit EnergíaDisipada_Rigidez_Col', 'Lower bounds (Fit EnergíaDisipada_Rigidez_Col)', 'Upper bounds (Fit EnergíaDisipada_Rigidez_Col)', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'E', 'Interpreter', 'none' );
% ylabel( 'Ks1', 'Interpreter', 'none' );
% grid on


