function [fitresult, gof] = Fit_Energia_Rigidez_Colmenares(E, Ks1)
%CREATEFIT(E,KS1)
%  Create a fit.
%
%  Data for 'Fit EnergíaDisipada_Rigidez_Col_lineal' fit:
%      X Input : E
%      Y Output: Ks1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Dec-2022 00:27:25


%% Fit: 'Fit EnergíaDisipada_Rigidez_Col_lineal'.
[xData, yData] = prepareCurveData( E, Ks1 );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% % Plot fit with data.
% figure( 'Name', 'Fit EnergíaDisipada_Rigidez_Col_lineal' );
% h = plot( fitresult, xData, yData, 'predobs', 0.9 );
% legend( h, 'Ks1 vs. E', 'Fit EnergíaDisipada_Rigidez_Col_lineal', 'Lower bounds (Fit EnergíaDisipada_Rigidez_Col_lineal)', 'Upper bounds (Fit EnergíaDisipada_Rigidez_Col_lineal)', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'E', 'Interpreter', 'none' );
% ylabel( 'Ks1', 'Interpreter', 'none' );
% grid on


