function [fitresult, gof] = Fit_Energia_Rigidez_SinDano_Incremental(E, Ks1)
%CREATEFIT(E,KS1)
%  Create a fit.
%
%  Data for 'Fit EnergíaDisipada_Rigidez' fit:
%      X Input : E
%      Y Output: Ks1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 30-Nov-2022 23:55:53


%% Fit: 'Fit EnergíaDisipada_Rigidez'.
[xData, yData] = prepareCurveData( E, Ks1 );

% Set up fittype and options.
ft = fittype( 'power2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.41024978196605 -0.319287265265456 0.0387106978153809];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'Fit EnergíaDisipada_Rigidez' );
% h = plot( fitresult, xData, yData, 'predobs', 0.9 );
% legend( h, 'Ks1 vs. E', 'Fit EnergíaDisipada_Rigidez', 'Lower bounds (Fit EnergíaDisipada_Rigidez)', 'Upper bounds (Fit EnergíaDisipada_Rigidez)', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'E', 'Interpreter', 'none' );
% ylabel( 'Ks1', 'Interpreter', 'none' );
% grid on


